[package]
name = "bevy_simple_text_input"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Bevy plugin for a simple single-line text input widget."
repository = "https://github.com/rparrett/bevy_simple_text_input"
homepage = "https://github.com/rparrett/bevy_simple_text_input"
documentation = "https://docs.rs/bevy_simple_text_input"
keywords = ["bevy", "gamedev"]
categories = ["game-development"]
readme = "README.md"
exclude = ["assets", ".github"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
